### ISSUE TITLE
[Bug]: Don't kill a VASP job if NBANDS is very high with no other warning

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/custodian#344]
### What happened?

In the following block of code, if VASP updates the number of bands automatically and it's > 2x the number of electrons, Custodian will kill the job even if VASP completes with no errors.

https://github.com/materialsproject/custodian/blob/880ca8b96ec3adfe57497b4cba1b72242db8be83/src/custodian/vasp/handlers.py#L727-L736

In practice, having such a large number of bands is a sign of a problem by the user and can lead to spurious energetic states. I have observed this for gas-phase CO in a box. But we ultimately should not kill the job. We should just warn the user (even though it's unlikely they'll read the logs). 

This was indirectly noted by @esoteric-ephemera in https://github.com/materialsproject/custodian/pull/342.

I can patch this, but it admittedly won't be for a little while. We should rethink how the bands stuff is being handled because in practice, it doesn't actually seem ideal...

### Version

v2024.6.24

### Which OS?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

**Comment by Andrew-S-Rosen** [comment]
My proposal is as follows.

Remove `auto_nbands` from the `error_msgs` list. It is not an error but rather just a useful warning from VASP.

https://github.com/materialsproject/custodian/blob/880ca8b96ec3adfe57497b4cba1b72242db8be83/src/custodian/vasp/handlers.py#L140

Remove the `if "auto_nbands" check:

https://github.com/materialsproject/custodian/blob/880ca8b96ec3adfe57497b4cba1b72242db8be83/src/custodian/vasp/handlers.py#L727

Instead, have the following block of checks be done in a "bespoke" manner where it is not tied to a specific VASP warning or error message:

https://github.com/materialsproject/custodian/blob/880ca8b96ec3adfe57497b4cba1b72242db8be83/src/custodian/vasp/handlers.py#L728-L751

This probably means we should be treating this as a new handler. Just like how we have an `UnconvergedErrorHandler` that checks for convergence, we can have an `NbandsErrorHandler` that checks for the appropriateness of nbands independent of any specific VASP error message.

**Comment by shyuep** [comment]
This has been fixed. But I have added a update_incar setting for VaspJob that solves this problem to some extent.

**Comment by yuan-gist** [comment]
I encountered a Custodian nbands issue when running the Lobster workflow: [issue](https://github.com/JaGeo/LobsterPy/issues/348)

As long as there is enough number of basis functions, the number of empty bands should not be issue, so I do not think Custodian should settle in when NBANDS is automatically changed by VASP.

**Comment by shyuep** [comment]
This was already fixed in the latest custodian release.

**Comment by yuan-gist** [comment]
Sorry, forgot to mention my Custodian version is `2024.10.16`, which is the latest. It seems the issue is still there, though I have not try update_incar setting for this.

**Comment by JaGeo** [comment]
@shyuep thanks for the help!
